version: 0.2

env:
  SONAR_PROJECT_NAME : "abdullah-kimrigh-java-maven-app"
  SONAR_IP : "35.172.191.120"
  SONAR_TOKEN : "sqp_5dee806dc2f00df8c35b66506157423930651a74"

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      java: corretto17
  pre_build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    - mvn clean
    - mvn validate
    - echo Build ends on 'date'
  build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    - mvn compile
    - mvn test
    - echo Build ends on 'date'
  post_build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    # - mvn clean verify sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_NAME -Dsonar.host.url=http://$SONAR_IP -Dsonar.login=$SONAR_TOKEN
    - mvn package
    - mv target/*.jar ROOT.jar
    - echo Build ends on 'date'

artifacts:
  files:
    - ROOT.jar
  name: hello-world-artifact